### ISSUE TITLE
Exception: "Wrong tab configuration" with Magento 1.9.2.4

### ISSUE THREAD

**Issue by OnyXxL** [yvoronoy/magento-extension-extra-fee#7]
I experienced issue in Magento 1.9.2.4 when I try to access the "Cart rules" tab in the back-end.

Here are the exception logs:    

```
URL: http://dev.mystore.fr/magento/index.php/my-storeadm/promo_quote/new/key/94f8f32a36c2fa8a79470017c6e0feb1/
IP Address: 192.168.1.100
Time: 2016-05-11 22:28:03 GMT
Error:
Wrong tab configuration.

Trace:
#0 [internal function]: Mage_Adminhtml_Block_Widget_Tabs->addTab('actions_section', 'promo_quote_edi...')
#1 /usr/home/www/my-store-dev/magento/app/code/community/Codnitive/Extifcon/Model/Core/Layout.php(132): call_user_func_array(Array, Array)
#2 /usr/home/www/my-store-dev/magento/app/code/community/Codnitive/Extifcon/Model/Core/Layout.php(70): Codnitive_Extifcon_Model_Core_Layout->_runAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#3 /usr/home/www/my-store-dev/magento/app/code/local/Mage/Core/Model/Layout.php(214): Codnitive_Extifcon_Model_Core_Layout->_generateAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#4 /usr/home/www/my-store-dev/magento/app/code/local/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#5 /usr/home/www/my-store-dev/magento/app/code/local/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#9 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Adminhtml/controllers/Promo/QuoteController.php(48): Mage_Adminhtml_Controller_Action->loadLayout()
#10 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Adminhtml/controllers/Promo/QuoteController.php(97): Mage_Adminhtml_Promo_QuoteController->_initAction()
#11 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Promo_QuoteController->editAction()
#12 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#13 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 /usr/home/www/my-store-dev/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#15 /usr/home/www/my-store-dev/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#16 /usr/home/www/my-store-dev/magento/index.php(83): Mage::run('', 'store')
#17 {main}
```

I'm using PHP7.0.6 and Apache 2.4 but I tried with PHP 5 without success too.

**Comment by yvoronoy** [comment]
As I can see from stacktrace you use overrided Layout Model in local scope and community 3rd party extension Codnitive_Extifcon.

On vanilla magento it works, so I propose you try to disable Codnitive_Extifcon extension or local Layout Model and check it should works.

Thanks
